name: m_kit
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  coverage: ^1.10.0
  test: ^1.25.7

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

   fonts:
     - family: yekan
       fonts:
         - asset: assets/fonts/yekan.ttf

     - family: dastnevis
       fonts:
         - asset: assets/fonts/danst_nevis.otf

     - family: iranSans
       fonts:
         - asset: assets/fonts/iran_sans.ttf

  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
